### ISSUE TITLE
Could you please share the 23 malicious seeds mentioned in your paper?

### ISSUE THREAD

**Issue by EvanXiaa** [Aurore54F/HideNoSeek#1]
Hello Fass！

This work has inspired me a lot. Recently I am working on JS obfuscation and I want to test see if the obfuscated code preserve its functionality. I think the malicious seeds you chose are representative for this validity test. I really appreciate if you could share me a copy.

Anyway, thank you in advance!

**Comment by Aurore54F** [comment]
Hi Anderson-Xia,

Thanks for reaching out!
Unfortunately, I don't have the initial malicious seeds anymore.

However, if you are interested I could share some seeds with you, but they do not contain the initial malicious payload, just a random string instead.
In this case, please send me an email with:
- your educational email address,
- your supervisor in CC,
- 1 sentence to explain what you'll do with the seeds.

Thanks!
A.

**Comment by EvanXiaa** [comment]
Thank you so much for that!
